version: '3'

vars:
  UV: uv
  RUN: .venv/bin/python -m
  SRC_DIR: src
  TEST_DIR: tests

tasks:

  install:
    desc: Install all dependencies (run this first)
    cmds:
      - task: _check-tools
      - task: _create-venv
      - task: _setup-local-agentecs
      - '{{.UV}} pip install -e ".[dev]"'
      - task: _frontend-install
      - task: frontend:build
      - task: _install-hooks
      - echo "Ready! Run 'task --list' for commands"

  test:
    desc: Run tests (pass args like --cov=src/agentecs_viz)
    cmds:
      - '{{.RUN}} pytest {{.CLI_ARGS}}'

  lint:
    desc: Lint and auto-fix code
    cmds:
      - '{{.RUN}} ruff check --fix {{.SRC_DIR}} {{.TEST_DIR}}'

  format:
    desc: Format code (use -- --check for check-only)
    cmds:
      - '{{.RUN}} ruff format {{.SRC_DIR}} {{.TEST_DIR}} {{.CLI_ARGS}}'

  typecheck:
    desc: Run mypy type checking
    cmds:
      - '{{.RUN}} mypy {{.SRC_DIR}}'

  check:
    desc: Run all checks (for CI)
    cmds:
      - '{{.RUN}} ruff format --check {{.SRC_DIR}} {{.TEST_DIR}}'
      - '{{.RUN}} ruff check {{.SRC_DIR}} {{.TEST_DIR}}'
      - '{{.RUN}} mypy {{.SRC_DIR}}'
      - '{{.RUN}} pytest'
      - task: frontend:check

  serve:
    desc: Start server with mock data
    deps: [frontend:build]
    cmds:
      - '.venv/bin/agentecs-viz serve --mock {{.CLI_ARGS}}'

  build:
    desc: Build wheel with bundled frontend
    deps: [frontend:build]
    cmds:
      - '{{.UV}} build --wheel'
      - echo "Built dist/agentecs_viz-*.whl"

  frontend:dev:
    desc: Start frontend dev server (hot reload)
    dir: frontend
    cmds:
      - npm run dev

  frontend:build:
    desc: Build frontend for production
    dir: frontend
    sources:
      - src/**/*
      - package.json
      - vite.config.ts
      - tsconfig.json
    generates:
      - dist/**/*
    cmds:
      - npm run build

  frontend:test:
    desc: Run frontend tests
    dir: frontend
    cmds:
      - npx vitest run {{.CLI_ARGS}}

  frontend:check:
    desc: Run frontend type checking and tests
    dir: frontend
    cmds:
      - npm run check
      - npx vitest run

  clean:
    desc: Remove all build artifacts (add --all for venv too)
    cmds:
      - 'rm -rf build/ dist/ *.egg-info .pytest_cache/ .mypy_cache/ .ruff_cache/ htmlcov/ .coverage src/agentecs_viz/frontend/'
      - 'find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true'
      - 'test "{{.CLI_ARGS}}" = "--all" && rm -rf .venv/ frontend/node_modules/ frontend/dist/ && echo "Cleaned all" || echo "Cleaned (--all for venv)"'

  # === Internal tasks ===

  _check-tools:
    internal: true
    cmds:
      - 'command -v {{.UV}} >/dev/null 2>&1 || { echo "Error: uv not found"; exit 1; }'
      - 'command -v npm >/dev/null 2>&1 || { echo "Error: npm not found"; exit 1; }'
    silent: true

  _create-venv:
    internal: true
    cmds:
      - '{{.UV}} venv'
    status:
      - test -d .venv

  _setup-local-agentecs:
    internal: true
    cmds:
      - 'test -d "../agentecs" && echo "Installing local agentecs" && {{.UV}} pip install -e ../agentecs || true'
    silent: true

  _frontend-install:
    internal: true
    dir: frontend
    cmds:
      - npm install
    status:
      - test -d node_modules

  _install-hooks:
    internal: true
    cmds:
      - '.venv/bin/pre-commit install'
    status:
      - test -f .git/hooks/pre-commit
